Imported Upstream version 0.10.6

diff --git a/tests/full-test b/tests/full-test
--- a/tests/full-test
+++ b/tests/full-test
@@ -26,14 +26,14 @@ if [ $? != 0 ];then
 	exit 77
 fi
 
-PORT_OCSERV=5551
+PORT_OCSERV=443
 CONFIG="tcp"
 IMAGE=ocserv-test1
 IMAGE_NAME=test_ocserv
 TMP=$IMAGE_NAME.tmp
 . ./docker-common.sh
 
-$DOCKER run -P --privileged=true -p 5000:5000/udp -p 5001:5001/udp -p 22 -p 5551:5551/udp --tty=false -d --name test_ocserv $IMAGE
+$DOCKER run -e OCCTL_PAGER=cat -P --privileged=true -p 22 --tty=false -d --name $IMAGE_NAME $IMAGE
 if test $? != 0;then
 	echo "Cannot run docker image"
 	exit 1
@@ -43,7 +43,7 @@ echo "ocserv image was run"
 #wait for ocserv to server
 sleep 5
 
-IP=`$DOCKER inspect test_ocserv | grep IPAddress | cut -d '"' -f 4`
+IP=`$DOCKER inspect $IMAGE_NAME | grep IPAddress | cut -d '"' -f 4`
 if test -z "$IP";then
 	echo "Detected IP is null!"
 	stop
@@ -54,96 +54,80 @@ if test ! -z "$QUIT_ON_INIT";then
 	exit 0
 fi
 
-printf "testuser\n" >pass-full$TMP
+$ECHO_E "testuser" >pass-full$TMP
 $OPENCONNECT $IP:$PORT_OCSERV -u test --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly < pass-full$TMP
 if test $? = 0;then
 	echo "Authentication with wrong password succeeded!"
 	stop
 fi
 
-printf "test\n" >pass-full$TMP
+$ECHO_E "test" >pass-full$TMP
 $OPENCONNECT $IP:$PORT_OCSERV -u testuser --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly < pass-full$TMP
 if test $? = 0;then
 	echo "Authentication with wrong username succeeded!"
 	stop
 fi
 
-printf "test\n" >pass-full$TMP
-$OPENCONNECT $IP:$PORT_OCSERV -u test --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 < pass-full$TMP &
-PID=$!
-
-rm -f pass-full$TMP
+echo ""
+echo "Connecting with correct username"
+$ECHO_E "test" >pass-full$TMP
+$OPENCONNECT $IP:$PORT_OCSERV -b --pid-file ${srcdir}/pid1.$$ -u test --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 < pass-full$TMP
+if test $? != 0;then
+	echo "Cannot connect to server"
+	stop
+fi
 
 #wait for openconnect
 sleep 5
 
+rm -f pass-full$TMP
+if [ ! -f ${srcdir}/pid1.$$ ];then
+	echo "It was not possible to establish session!"
+	stop
+fi
+
+PID=`cat ${srcdir}/pid1.$$`
+
 # The client IP depends on the username so it shouldn't change.
-ping -w 5 192.168.1.1
+ping -w 5 192.168.79.1
 if test $? != 0;then
 	kill $PID
 	echo "Cannot ping ocserv"
 	stop
 fi
 
-ping -w 5 192.168.1.1 -s 1500
+ping -w 5 192.168.79.1 -s 1500
 if test $? != 0;then
 	kill $PID
 	echo "Cannot ping ocserv"
 	stop
 fi
 
-ping6 -w 5 fd91:6d87:7341:db6a::1
+ping6 -w 5 fd91:6d87:7341:db6a:0:52:190c:be01
 if test $? != 0;then
 	kill $PID
 	echo "Cannot ping the IPv6 of ocserv"
 	stop
 fi
 
-echo "UserKnownHostsFile ./known-hosts$TMP" >config$TMP
-printf "#\!/bin/sh\n" >echo-admin$TMP
-printf "echo yes" >>echo-admin$TMP
-printf "echo root" >>echo-admin$TMP
-printf "\n" >>echo-admin$TMP
-chmod 755 echo-admin$TMP
-export SSH_ASKPASS="./echo-admin$TMP"
-setsid ssh -T -F config$TMP root@192.168.1.1 occtl show user test >out$TMP 2>&1
-cat out$TMP
-
-printf "#\!/bin/sh\n" >echo-admin$TMP
-printf "echo root" >>echo-admin$TMP
-printf "\n" >>echo-admin$TMP
-chmod 755 echo-admin$TMP
-setsid ssh -T -F config$TMP root@192.168.1.1 occtl show users
-setsid ssh -T -F config$TMP root@192.168.1.1 occtl show user test >out$TMP 2>&1
-cat out$TMP
-rm -f echo-admin$TMP
-rm -f config$TMP
-rm -f known-hosts$TMP
-
-grep "Username" out$TMP
-if test $? != 0;then
-	kill $PID
-	cat out$TMP
-	echo "could not find user information"
-	stop
-fi
-
-rm -f out$TMP
+retrieve_user_info test
 
 # There is an issue in nuttcp that makes it crash under docker if
 # /proc/sys/net/ipv4/tcp_adv_win_scale does not exist.
 if test "$FEDORA" = 1;then
-nuttcp -T 10 -t 192.168.1.1
+nuttcp -T 10 -t 192.168.79.1
 if test $? != 0;then
-	kill $PID
 	echo "Cannot send to ocserv"
+	exit 77
+	kill $PID
 	stop
 fi
 
-nuttcp -T 10 -r 192.168.1.1
+nuttcp -T 10 -r 192.168.79.1
 if test $? != 0;then
-	kill $PID
 	echo "Cannot recv from ocserv"
+	exit 77
+	kill $PID
 	stop
 fi
 fi
@@ -155,28 +139,19 @@ kill $PID
 sleep 4
 
 #check whether /tmp/disconnect/ok was created
-rm -f ./not-ok
-$DOCKER cp test_ocserv:/tmp/disconnect/not-ok ./
-if test -f ./not-ok;then
-	echo "There was an issue getting stats"
+check_for_file /tmp/disconnect/not-ok
+if test $? = 0;then
+	echo "There was an issue"
 	stop
 fi
-rm -f ./not-ok
 
-ret=0
-
-rm -f ./tmp-full/ok
-$DOCKER cp test_ocserv:/tmp/disconnect/ok ./tmp-full/
-if ! test -f ./tmp-full/ok;then
-	echo "Don't know if stats were received"
+check_for_file /tmp/disconnect/ok
+if test $? != 0;then
+	echo "There was an issue getting stats"
 	ret=77
-else
-	echo -n "stats: "
-	echo `cat ./tmp-full/ok`
-	rm -rf ./tmp-full/
 fi
 
-$DOCKER stop test_ocserv
-$DOCKER rm test_ocserv
+$DOCKER stop $IMAGE_NAME
+$DOCKER rm $IMAGE_NAME
 
 exit $ret
diff --git a/tests/radius-test b/tests/radius-test
--- a/tests/radius-test
+++ b/tests/radius-test
@@ -35,7 +35,7 @@ IMAGE_NAME=test_ocserv_radius
 TMP=$IMAGE_NAME.tmp
 . ./docker-common.sh
 
-$DOCKER run -P --privileged=true -p $PORT:$PORT/udp -p $PORT2:$PORT2/udp -p 22 -p $PORT_OCSERV:$PORT_OCSERV/udp --tty=false -d --name test_ocserv_radius $IMAGE
+$DOCKER run -e OCCTL_PAGER=cat -P --privileged=true --tty=false -d --name $IMAGE_NAME $IMAGE
 if test $? != 0;then
 	echo "Cannot run docker image"
 	exit 1
@@ -45,7 +45,7 @@ echo "ocserv image was run"
 #wait for ocserv to server
 sleep 5
 
-IP=`$DOCKER inspect test_ocserv_radius | grep IPAddress | cut -d '"' -f 4`
+IP=`$DOCKER inspect $IMAGE_NAME | grep IPAddress | cut -d '"' -f 4`
 if test -z "$IP";then
 	echo "Detected IP is null!"
 	stop
@@ -56,14 +56,14 @@ if test ! -z "$QUIT_ON_INIT";then
 	exit 0
 fi
 
-printf "testuser\n" >pass-radius$TMP
+$ECHO_E "testuser" >pass-radius$TMP
 $OPENCONNECT $IP:$PORT_OCSERV -u test --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly < pass-radius$TMP
 if test $? = 0;then
 	echo "Authentication with wrong password succeeded!"
 	stop
 fi
 
-printf "test\n" >pass-radius$TMP
+$ECHO_E "test" >pass-radius$TMP
 $OPENCONNECT $IP:$PORT_OCSERV -u testuser --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly < pass-radius$TMP
 if test $? = 0;then
 	echo "Authentication with wrong username succeeded!"
@@ -71,7 +71,7 @@ if test $? = 0;then
 fi
 
 echo "Trying with correct password"
-printf "test\n" >pass-radius$TMP
+$ECHO_E "test" >pass-radius$TMP
 $OPENCONNECT $IP:$PORT_OCSERV -u test --passwd-on-stdin -v --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 < pass-radius$TMP &
 PID=$!
 
@@ -95,41 +95,14 @@ if test $? != 0;then
 	stop
 fi
 
-ping6 -w 5 fd91:6d87:7341:dd6b::1
+ping6 -w 5 fd91:6d87:7341:dd6b:0:52:190c:be01
 if test $? != 0;then
 	kill $PID
 	echo "Cannot ping the IPv6 of ocserv"
 	stop
 fi
 
-echo "UserKnownHostsFile ./known-hosts$TMP" >config$TMP
-printf "#\!/bin/sh\n" >echo-admin$TMP
-printf "echo yes" >>echo-admin$TMP
-printf "echo root" >>echo-admin$TMP
-printf "\n" >>echo-admin$TMP
-chmod 755 echo-admin$TMP
-export SSH_ASKPASS="./echo-admin$TMP"
-setsid ssh -T -F config$TMP root@192.168.55.1 occtl show user test >out$TMP 2>&1
-cat out$TMP
-
-printf "#\!/bin/sh\n" >echo-admin$TMP
-printf "echo root" >>echo-admin$TMP
-printf "\n" >>echo-admin$TMP
-chmod 755 echo-admin$TMP
-setsid ssh -T -F config$TMP root@192.168.55.1 occtl show user test >out$TMP 2>&1
-cat out$TMP
-rm -f echo-admin$TMP
-rm -f config$TMP
-rm -f known-hosts$TMP
-
-grep "Username" out$TMP
-if test $? != 0;then
-	kill $PID
-	echo "could not find user information"
-	stop
-fi
-
-rm -f out$TMP
+retrieve_user_info test
 
 # There is an issue in nuttcp that makes it crash under docker if
 # /proc/sys/net/ipv4/tcp_adv_win_scale does not exist.
@@ -152,47 +125,109 @@ fi
 echo "Waiting for accounting report"
 sleep 60
 
-kill $PID
+kill -INT $PID
 
 sleep 4
 
-TMPDIR=radius-$TMP
-mkdir -p $TMPDIR
-#check whether /tmp/disconnect/ok was created
-rm -f $TMPDIR/not-ok
-$DOCKER cp test_ocserv_radius:/tmp/disconnect/not-ok $TMPDIR/
-if test -f $TMPDIR/not-ok;then
+check_for_file /tmp/disconnect/not-ok
+if test $? = 0;then
+	echo "There was an issue"
+	stop
+fi
+
+FILE=`$DOCKER exec $IMAGE_NAME ls /var/log/radius/radacct/127.0.0.1/`
+
+OCTETS=`$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"|grep Acct-Input-Octets|tail -1|sed 's/Acct-Input-Octets = //g'`
+if test -z "$OCTETS" || test "$OCTETS" = 0;then
+	$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"
+	echo "Interim update showed no data!"
+	stop
+fi
+
+check_for_file /tmp/disconnect/ok
+if test $? != 0;then
+	$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"
 	echo "There was an issue getting stats"
 	stop
 fi
-rm -f $TMPDIR/not-ok
 
-rm -f $TMPDIR/stats
+ret=0
 
-FILE=`$DOCKER exec test_ocserv_radius ls /var/log/radius/radacct/127.0.0.1/`
-echo $DOCKER exec test_ocserv_radius cat "/var/log/radius/radacct/127.0.0.1/$FILE"
-$DOCKER exec test_ocserv_radius cat "/var/log/radius/radacct/127.0.0.1/$FILE"
+#wait until sec-mod has cleaned up its entries
+echo "Waiting for disconnection report"
+sleep 10
+DISC=`$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"|grep "Acct-Terminate-Cause = User-Request"|tail -1`
+if test -z "$DISC";then
+	$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE"
+	echo "No disconnect was detected!"
+	stop
+fi
 
-OCTETS=`$DOCKER exec test_ocserv_radius cat "/var/log/radius/radacct/127.0.0.1/$FILE"|grep Acct-Input-Octets|tail -1|sed 's/Acct-Input-Octets = //g'`
+# do the same with a certificate - test radius accounting with certificate auth
+echo "Trying with certificate"
+rm -f out$TMP.pid
+$DOCKER exec $IMAGE_NAME truncate --size=0 /var/log/radius/radacct/127.0.0.1/$FILE
+$OPENCONNECT $IP:$PORT_OCSERV -b --sslkey ./user-key.pem -c ./user-cert.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --pid-file=out$TMP.pid
+
+sleep 10
+
+if test -f out$TMP.pid;then
+	PID=`cat out$TMP.pid`
+else
+	echo "Cannot determine PID of client"
+	stop
+fi	
+
+ping -w 5 192.168.55.1
+if test $? != 0;then
+	kill $PID
+	echo "Cannot ping ocserv"
+	stop
+fi
+
+
+sleep 4
+
+echo "Waiting for accounting report"
+sleep 60
+
+kill -INT $PID
+
+sleep 10
+
+FILE=`$DOCKER exec $IMAGE_NAME ls /var/log/radius/radacct/127.0.0.1/|tail -1`
+$DOCKER exec $IMAGE_NAME cat "/var/log/radius/radacct/127.0.0.1/$FILE" >out$TMP
+cat out$TMP
+OCTETS=`cat out$TMP|grep Acct-Input-Octets|tail -1|sed 's/Acct-Input-Octets = //g'`
 if test -z "$OCTETS" || test "$OCTETS" = 0;then
 	echo "Interim update showed no data!"
 	stop
 fi
 
-rm -f $TMPDIR/ok
-$DOCKER cp test_ocserv_radius:/tmp/disconnect/ok $TMPDIR/
-if ! test -f $TMPDIR/ok;then
-	echo "Don't know if stats were received"
-	ret=77
-else
-	echo -n "stats: "
-	echo `cat $TMPDIR/ok`
-	rm -rf $TMPDIR/
+DISC=`cat out$TMP|grep "Acct-Status-Type = Start"|tail -1`
+if test -z "$DISC";then
+	cat out$TMP
+	echo "No connect status was detected!"
+	stop
 fi
 
-ret=0
+DISC=`cat out$TMP|grep "Acct-Terminate-Cause = User-Request"|tail -1`
+if test -z "$DISC";then
+	cat out$TMP
+	echo "No disconnect was detected!"
+	stop
+fi
 
-$DOCKER stop test_ocserv_radius
-$DOCKER rm test_ocserv_radius
+DISC=`cat out$TMP|grep "NAS-IP-Address = 127.0.0.1"|tail -1`
+if test -n "$DISC";then
+	cat out$TMP
+	echo "NAS-IP-Address has invalid value!"
+	stop
+fi
+
+$DOCKER stop $IMAGE_NAME
+$DOCKER rm $IMAGE_NAME
+
+rm -f out$TMP
 
 exit $ret
